import 'dart:typed_data';

import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../data/catalog_repository.dart';
import '../models/episode.dart';
import '../providers/insights_provider.dart';

/// Builds the clinical doctor report PDF. Clean light layout on white paper,
/// intentionally separate from the dark app.
class PdfService {
  PdfService(this._catalog);

  final CatalogRepository _catalog;

  // Clinical palette (light document).
  static const _ink = PdfColor.fromInt(0xFF1A1A1A);
  static const _muted = PdfColor.fromInt(0xFF6B6B6B);
  static const _line = PdfColor.fromInt(0xFFE2E2E2);
  static const _accent = PdfColor.fromInt(0xFFC9794A);
  static const _band = PdfColor.fromInt(0xFFF5F1EC);

  Future<Uint8List> build({
    required List<Episode> episodes,
    required Insights insights,
    required String rangeLabel,
    String? patientName,
  }) async {
    final doc = pw.Document();
    final df = DateFormat('d MMM yyyy');
    final dft = DateFormat('d MMM yyyy, h:mm a');
    final generated = DateFormat('d MMM yyyy').format(DateTime.now());

    // Sort chronologically for the table.
    final sorted = [...episodes]
      ..sort((a, b) => a.startAt.compareTo(b.startAt));

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(36),
        header: (context) => context.pageNumber == 1
            ? pw.SizedBox()
            : pw.Container(
                alignment: pw.Alignment.centerRight,
                margin: const pw.EdgeInsets.only(bottom: 8),
                child: pw.Text('Headache & Migraine Report',
                    style: pw.TextStyle(fontSize: 9, color: _muted)),
              ),
        footer: (context) => pw.Container(
          alignment: pw.Alignment.center,
          margin: const pw.EdgeInsets.only(top: 8),
          child: pw.Text(
            'Generated by Nerok. For tracking only, not a medical diagnosis.   ·   Page ${context.pageNumber} of ${context.pagesCount}',
            style: pw.TextStyle(fontSize: 8, color: _muted),
          ),
        ),
        build: (context) => [
          _header(patientName, rangeLabel, generated, df),
          pw.SizedBox(height: 18),
          _summaryTiles(insights),
          pw.SizedBox(height: 18),
          _weeklyChart(insights),
          pw.SizedBox(height: 18),
          _episodeTable(sorted, dft),
          pw.SizedBox(height: 18),
          _triggerTable(insights),
        ],
      ),
    );

    return doc.save();
  }

  pw.Widget _header(
      String? patient, String range, String generated, DateFormat df) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Headache & Migraine Report',
          style: pw.TextStyle(
            fontSize: 24,
            fontWeight: pw.FontWeight.bold,
            color: _ink,
          ),
        ),
        pw.SizedBox(height: 6),
        pw.Container(height: 3, width: 60, color: _accent),
        pw.SizedBox(height: 10),
        pw.Row(
          children: [
            if (patient != null && patient.isNotEmpty)
              _metaItem('Patient', patient),
            _metaItem('Date range', range),
            _metaItem('Generated', generated),
          ],
        ),
      ],
    );
  }

  pw.Widget _metaItem(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(right: 24),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(label.toUpperCase(),
              style: pw.TextStyle(fontSize: 7, color: _muted)),
          pw.SizedBox(height: 2),
          pw.Text(value,
              style: pw.TextStyle(
                  fontSize: 11,
                  color: _ink,
                  fontWeight: pw.FontWeight.bold)),
        ],
      ),
    );
  }

  pw.Widget _summaryTiles(Insights insights) {
    final avgDur = _formatDuration(insights.avgDuration);
    final tiles = [
      ('Total episodes', '${insights.episodeCount}'),
      ('Avg intensity', insights.avgIntensity.toStringAsFixed(1)),
      ('Avg duration', avgDur),
      ('Episodes / week', insights.episodesPerWeek.toStringAsFixed(1)),
    ];
    return pw.Row(
      children: [
        for (final t in tiles)
          pw.Expanded(
            child: pw.Container(
              margin: const pw.EdgeInsets.only(right: 8),
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                color: _band,
                borderRadius: pw.BorderRadius.circular(8),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Text(t.$2,
                      style: pw.TextStyle(
                          fontSize: 20,
                          fontWeight: pw.FontWeight.bold,
                          color: _ink)),
                  pw.SizedBox(height: 2),
                  pw.Text(t.$1,
                      style: pw.TextStyle(fontSize: 8, color: _muted)),
                ],
              ),
            ),
          ),
      ],
    );
  }

  pw.Widget _weeklyChart(Insights insights) {
    final buckets = insights.weekBuckets;
    final max =
        buckets.fold<int>(1, (m, b) => b.count > m ? b.count : m);
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Episodes per week'),
        pw.SizedBox(height: 8),
        pw.Container(
          height: 110,
          decoration: pw.BoxDecoration(
            border: pw.Border(bottom: pw.BorderSide(color: _line)),
          ),
          child: pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              for (final b in buckets)
                pw.Expanded(
                  child: pw.Padding(
                    padding: const pw.EdgeInsets.symmetric(horizontal: 1.5),
                    child: pw.Column(
                      mainAxisAlignment: pw.MainAxisAlignment.end,
                      children: [
                        pw.Text(
                          b.count == 0 ? '' : '${b.count}',
                          style: pw.TextStyle(fontSize: 6, color: _muted),
                        ),
                        pw.SizedBox(height: 1),
                        pw.Container(
                          height: (b.count / max) * 88,
                          decoration: pw.BoxDecoration(
                            color: _accent,
                            borderRadius: const pw.BorderRadius.vertical(
                                top: pw.Radius.circular(2)),
                          ),
                        ),
                      ],
                    ),
                  ),
                ),
            ],
          ),
        ),
      ],
    );
  }

  pw.Widget _episodeTable(List<Episode> episodes, DateFormat dft) {
    final headers = [
      'Date',
      'Start–End',
      'Dur.',
      'Int.',
      'Type',
      'Triggers',
      'Relief',
      'Meds',
    ];
    final rows = episodes.map((e) {
      return [
        DateFormat('d MMM').format(e.startAt),
        e.isOngoing
            ? '${DateFormat('h:mm a').format(e.startAt)} – ongoing'
            : '${DateFormat('h:mm a').format(e.startAt)} – ${DateFormat('h:mm a').format(e.endAt!)}',
        _formatDuration(e.duration),
        '${e.intensity}',
        e.type.label,
        _names(e.triggerIds),
        _names(e.reliefIds),
        e.meds.map((m) => m.name).join(', '),
      ];
    }).toList();

    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Episode log'),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headers: headers,
          data: rows.isEmpty
              ? [
                  ['—', '—', '—', '—', '—', '—', '—', '—']
                ]
              : rows,
          headerStyle: pw.TextStyle(
              fontSize: 8, fontWeight: pw.FontWeight.bold, color: _ink),
          headerDecoration: const pw.BoxDecoration(color: _band),
          cellStyle: pw.TextStyle(fontSize: 7.5, color: _ink),
          cellAlignment: pw.Alignment.centerLeft,
          cellPadding:
              const pw.EdgeInsets.symmetric(horizontal: 4, vertical: 4),
          border: pw.TableBorder.all(color: _line, width: 0.5),
          columnWidths: {
            0: const pw.FixedColumnWidth(42),
            1: const pw.FixedColumnWidth(78),
            2: const pw.FixedColumnWidth(34),
            3: const pw.FixedColumnWidth(24),
            4: const pw.FixedColumnWidth(48),
          },
        ),
      ],
    );
  }

  pw.Widget _triggerTable(Insights insights) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        _sectionTitle('Trigger frequency'),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headers: ['Trigger', 'Count'],
          data: insights.topTriggers.isEmpty
              ? [
                  ['No triggers logged', '—']
                ]
              : insights.topTriggers
                  .map((t) => [t.name, '${t.count}'])
                  .toList(),
          headerStyle: pw.TextStyle(
              fontSize: 8, fontWeight: pw.FontWeight.bold, color: _ink),
          headerDecoration: const pw.BoxDecoration(color: _band),
          cellStyle: pw.TextStyle(fontSize: 8, color: _ink),
          cellAlignment: pw.Alignment.centerLeft,
          cellPadding:
              const pw.EdgeInsets.symmetric(horizontal: 6, vertical: 4),
          border: pw.TableBorder.all(color: _line, width: 0.5),
          columnWidths: {
            0: const pw.FlexColumnWidth(4),
            1: const pw.FlexColumnWidth(1),
          },
        ),
      ],
    );
  }

  pw.Widget _sectionTitle(String text) {
    return pw.Text(
      text,
      style: pw.TextStyle(
          fontSize: 13, fontWeight: pw.FontWeight.bold, color: _ink),
    );
  }

  String _names(List<String> ids) {
    final names = ids
        .map((id) => _catalog.byId(id)?.name)
        .whereType<String>()
        .toList();
    return names.isEmpty ? '—' : names.join(', ');
  }

  String _formatDuration(Duration d) {
    if (d == Duration.zero) return '—';
    if (d.inHours >= 1) {
      final h = d.inHours;
      final m = d.inMinutes % 60;
      return m == 0 ? '${h}h' : '${h}h${m}m';
    }
    return '${d.inMinutes}m';
  }
}
